### ISSUE TITLE
Console app checklist

### ISSUE THREAD

**Issue by kbaley** [kbaley/Coronado#29]
- [ ] After selecting a vendor, pre-populate the category based on the last one used for the vendor (like the web app does)
- [ ] Support debit and credit for new transactions
- [ ] Ability to edit a transaction
- [ ] List invoices
- [ ] Create an invoice
- [ ] Email an invoice
- [ ] Sync investments with investment account
- [ ] Maybe some of the reports?
